CREATE TABLE [dbo].[FuneralPlans]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Religion] VARCHAR(20) NULL, 
    [RequireRites] BIT NULL, 
    [ConductOptions] VARCHAR(10) NULL, 
    [ReligiousPName] VARCHAR(100) NULL, 
    [ReligiousPOCName] VARCHAR(150) NULL, 
    [ReligiousPOCNumber] VARCHAR(8) NULL, 
    [WakeLocationIn] VARCHAR(20) NULL, 
    [WakePostalCode] VARCHAR(6) NULL, 
	[CasketID] SMALLINT NULL,
    [WakeDuration] SMALLINT NULL, 
    [PhotoFramed] VARCHAR(100) NULL, 
	[PhotoAttire] VARCHAR(100) NULL, 
    [LocationAttire] VARCHAR(256) NULL, 
    [WakeGuestsExpected] SMALLINT NULL, 
    [HasMakeupServices] BIT NULL, 
    [HasHairstylingServices] BIT NULL, 
    [HasMobileToilet] BIT NULL, 
    [HasBeverages] BIT NULL, 
    [HasTibits] BIT NULL, 
    [HasFridge] BIT NULL, 
    [HasLunch] BIT NULL, 
    [HasDinner] BIT NULL, 
    [HasRegisterBook] BIT NULL, 
    [HasMemorialFolders] BIT NULL, 
	[FuneralVechicle] VARCHAR(30) NULL, 
    [HasMemorialService] BIT NULL, 
    [HasBusCatering] BIT NULL, 
    [HasFuneralCermony] BIT NULL,
	[FGuestsExpected] SMALLINT NULL,
    [FinalRestingPlace] VARCHAR(50) NULL, 
    [ColumbariumName] VARCHAR(100) NULL,
	[PlaquePhoto] VARCHAR(100) NULL,
	[PlaqueName] VARCHAR(100) NULL,
	[PlaqueHasBday] BIT NULL,
	[PlaqueHasDday] BIT NULL,
	[PlaqueQuotes] VARCHAR(170) NULL,
	[UrnId] SMALLINT NULL, 
    [PaymentAmount] FLOAT NOT NULL,
    [HasExecutorVerifiedWake] BIT NULL, 
    [ExecutorID] INT NULL, 
    [WillMaker_ID] INT NULL, 
    [TimeStamp] DATETIME NOT NULL, 
    [LastUpdatedTime] DATETIME NOT NULL, 
    [LastUpdatedById] INT NULL,
	[IsDeleted]	BIT NOT NULL
)
